apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello.angularApp.fullname" . }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
data:
  default.conf: |-
    upstream hello_api {
      server {{ include "hello.httpGoServer.fullname" . }};
    }

    server {
      listen 8080;

      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
      }

      location /hello/ {
        proxy_pass http://hello_api;
        proxy_http_version 1.1;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
      }
    }
