apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello.angularApp.fullname" . }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.angularApp.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.angularApp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.angularApp.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.angularApp.securityContext | nindent 12 }}
          image: "{{ .Values.angularApp.image.repository }}:{{ .Values.angularApp.image.tag }}"
          imagePullPolicy: {{ .Values.angularApp.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.angularApp.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "hello.angularApp.fullname" . }}
            items:
              - key: default.conf
                path: default.conf
      {{- with .Values.angularApp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.angularApp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.angularApp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
