apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello.httpGoServer.fullname" . }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.httpGoServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.httpGoServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.httpGoServer.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.httpGoServer.securityContext | nindent 12 }}
          image: "{{ .Values.httpGoServer.image.repository }}:{{ .Values.httpGoServer.image.tag }}"
          imagePullPolicy: {{ .Values.httpGoServer.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
            {{- toYaml .Values.httpGoServer.resources | nindent 12 }}
      {{- with .Values.httpGoServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.httpGoServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.httpGoServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
